import { useCallback, useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { AlertCircle, ArrowRight, CheckCircle2, Eye, Pencil, Search, Trash2, UserCheck, Users, X } from 'lucide-react';
import Sidebar from '../../components/Sidebar.jsx';
import Header from '../../components/Header.jsx';
import { deleteLead, getLeadStats, getLeads, updateLead } from '../../services/leadService.js';
import './LeadManager.css';

const STAGES = ['new', 'qualified', 'contacted', 'proposal', 'won', 'lost'];
const LABELS = { new: 'New', qualified: 'Qualified', contacted: 'Contacted', proposal: 'Proposal', won: 'Won', lost: 'Lost' };
const asDate = (value) => value?.toDate?.() || (value ? new Date(value) : null);
const emptyStats = { total: 0, newThisWeek: 0, qualified: 0, won: 0 };

function LeadManager() {
  const { workspaceId } = useParams(); const [sidebarOpen, setSidebarOpen] = useState(false); const [leads, setLeads] = useState([]); const [stats, setStats] = useState(emptyStats); const [selected, setSelected] = useState(null); const [draft, setDraft] = useState(null); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  const load = useCallback(async () => { if (!workspaceId) return; setLoading(true); setError(''); const [leadResult, statResult] = await Promise.all([getLeads(workspaceId), getLeadStats(workspaceId)]); if (leadResult.success) setLeads(leadResult.leads); else setError(leadResult.error || 'Unable to load leads.'); if (statResult.success) setStats(statResult.stats); setLoading(false); }, [workspaceId]);
  useEffect(() => { load(); }, [load]);
  const openLead = (lead) => { setSelected(lead); setDraft({ ...lead, notes: lead.notes || '', nextFollowUp: lead.nextFollowUp || '', score: lead.score || 5 }); };
  const saveLead = async () => { setSaving(true); const updates = { name: draft.name, email: draft.email, phone: draft.phone || null, interest: draft.interest || '', notes: draft.notes, nextFollowUp: draft.nextFollowUp || null, status: draft.status, score: Number(draft.score) }; const result = await updateLead(workspaceId, draft.id, updates); setSaving(false); if (result.success) { setSuccess('Lead updated.'); setSelected(null); setDraft(null); load(); } else setError(result.error || 'Unable to update lead.'); };
  const moveNext = async (lead) => { const index = STAGES.indexOf(lead.status); if (index < 0 || index >= STAGES.length - 1) return; const result = await updateLead(workspaceId, lead.id, { status: STAGES[index + 1] }); if (result.success) load(); else setError(result.error); };
  const remove = async (lead) => { if (!confirm(`Delete ${lead.name}? This cannot be undone.`)) return; const result = await deleteLead(workspaceId, lead.id); if (result.success) { if (selected?.id === lead.id) { setSelected(null); setDraft(null); } load(); } else setError(result.error); };
  const visible = leads.filter((lead) => `${lead.name} ${lead.email} ${lead.phone || ''}`.toLowerCase().includes(search.toLowerCase()));
  const cards = [['Total leads', stats.total, Users, 'purple'], ['New this week', stats.newThisWeek, Eye, 'blue'], ['Qualified leads', stats.qualified, UserCheck, 'amber'], ['Won leads', stats.won, CheckCircle2, 'green']];
  return <div className="app"><Sidebar isOpen={sidebarOpen} onClose={() => setSidebarOpen(false)} /><main className="main-content"><Header onMenuClick={() => setSidebarOpen(true)} /><div className="content-area leads-page">
    <div className="leads-header"><div><h1>Lead Manager</h1><p>Track prospects from first contact through conversion.</p></div><label className="lead-search"><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search leads" /></label></div>
    {error && <div className="lead-alert error"><AlertCircle size={18} />{error}</div>}{success && <div className="lead-alert success"><CheckCircle2 size={18} />{success}</div>}
    {loading ? <div className="lead-stats lead-skeleton">{cards.map(([label]) => <div key={label}><span /><span /></div>)}</div> : <div className="lead-stats">{cards.map(([label, value, Icon, color]) => <div className="lead-stat" key={label}><span className={`lead-stat-icon ${color}`}><Icon size={20} /></span><div><p>{label}</p><strong>{value}</strong></div></div>)}</div>}
    <section className="crm-section"><div className="crm-heading"><h2>Lead pipeline</h2><span>{visible.length} leads</span></div>{!loading && leads.length === 0 ? <div className="lead-empty"><Users size={34} /><p>No leads yet. Share your public capture page to collect your first lead.</p><code>/capture/{workspaceId}</code></div> : <div className="lead-pipeline">{STAGES.map((stage) => <div className="pipeline-column" key={stage}><header><span>{LABELS[stage]}</span><b>{visible.filter((lead) => lead.status === stage).length}</b></header><div className="pipeline-cards">{visible.filter((lead) => lead.status === stage).map((lead) => { const date = asDate(lead.createdAt); return <article className="pipeline-card" key={lead.id} onClick={() => openLead(lead)}><strong>{lead.name}</strong><span>{lead.source || 'Unknown source'}</span><time>{date ? date.toLocaleDateString() : 'No date'}</time>{stage !== 'lost' && <button onClick={(event) => { event.stopPropagation(); moveNext(lead); }} disabled={stage === 'won'}>{stage === 'won' ? 'Converted' : <><span>Move</span><ArrowRight size={13} /></>}</button>}</article>; })}</div></div>)}</div>}</section>
    <section className="crm-section"><div className="crm-heading"><h2>All leads</h2></div>{visible.length ? <div className="lead-table-wrap"><table className="lead-table"><thead><tr><th>Name</th><th>Email</th><th>Phone</th><th>Source</th><th>Status</th><th>Score</th><th>Date added</th><th>Actions</th></tr></thead><tbody>{visible.map((lead) => { const date = asDate(lead.createdAt); return <tr key={lead.id}><td><strong>{lead.name}</strong></td><td>{lead.email}</td><td>{lead.phone || '—'}</td><td>{lead.source || 'Unknown'}</td><td><span className={`lead-status status-${lead.status}`}>{LABELS[lead.status] || lead.status}</span></td><td>{lead.score || 5}/10</td><td>{date ? date.toLocaleDateString() : '—'}</td><td><div className="lead-actions"><button title="View" onClick={() => openLead(lead)}><Eye size={15} /></button><button title="Edit" onClick={() => openLead(lead)}><Pencil size={15} /></button><button className="delete" title="Delete" onClick={() => remove(lead)}><Trash2 size={15} /></button></div></td></tr>; })}</tbody></table></div> : !loading && leads.length > 0 && <div className="lead-empty"><Search size={30} /><p>No leads match your search.</p></div>}</section>
    {draft && <><button className="lead-panel-backdrop" aria-label="Close lead details" onClick={() => { setSelected(null); setDraft(null); }} /><aside className="lead-detail-panel"><header><div><span>Lead details</span><h2>{draft.name}</h2></div><button onClick={() => { setSelected(null); setDraft(null); }}><X size={20} /></button></header><div className="lead-detail-body"><label>Name<input value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} /></label><label>Email<input type="email" value={draft.email} onChange={(e) => setDraft({ ...draft, email: e.target.value })} /></label><label>Phone<input value={draft.phone || ''} onChange={(e) => setDraft({ ...draft, phone: e.target.value })} /></label><label>Interest<textarea rows="3" value={draft.interest || ''} onChange={(e) => setDraft({ ...draft, interest: e.target.value })} /></label><div className="detail-two"><label>Status<select value={draft.status} onChange={(e) => setDraft({ ...draft, status: e.target.value })}>{STAGES.map((stage) => <option key={stage} value={stage}>{LABELS[stage]}</option>)}</select></label><label>Score<input type="number" min="1" max="10" value={draft.score} onChange={(e) => setDraft({ ...draft, score: e.target.value })} /></label></div><label>Next follow up<input type="date" value={draft.nextFollowUp || ''} onChange={(e) => setDraft({ ...draft, nextFollowUp: e.target.value })} /></label><label>Notes<textarea rows="5" value={draft.notes} onChange={(e) => setDraft({ ...draft, notes: e.target.value })} placeholder="Add notes about this lead..." /></label><section className="conversation-section"><h3>Conversation history</h3>{Array.isArray(draft.conversationHistory) && draft.conversationHistory.length ? draft.conversationHistory.map((message, index) => <div key={index}><strong>{message.sender || 'Team'}</strong><p>{message.message || message.text}</p></div>) : <p>No conversations recorded yet.</p>}</section><section className="next-action"><h3>Recommended next action</h3><p>{draft.recommendedNextAction || (draft.status === 'new' ? 'Reach out within 24 hours and confirm their needs.' : draft.status === 'qualified' ? 'Schedule a discovery call.' : draft.status === 'contacted' ? 'Send a useful follow-up and confirm next steps.' : draft.status === 'proposal' ? 'Follow up on the proposal and address objections.' : draft.status === 'won' ? 'Begin onboarding and request a referral.' : 'Record the reason the opportunity was lost.')}</p></section></div><footer><button className="panel-delete" onClick={() => remove(draft)}>Delete</button><button className="panel-save" onClick={saveLead} disabled={saving}>{saving ? 'Saving...' : 'Save changes'}</button></footer></aside></>}
  </div></main></div>;
}
export default LeadManager;
